name: CodSpeed

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmarks:
    name: CodSpeed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.95"
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-codspeed --locked
      - run: cargo codspeed build
      - uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: cargo codspeed run
